//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT
    {
        public string DeptId { get; set; }
        public string DeptName { get; set; }
        public string FactoryId { get; set; }
    }
}
