//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_computer_tran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_computer_tran()
        {
            this.ext26_assetcontrol_approve = new HashSet<ext26_assetcontrol_approve>();
        }
    
        public int id_computer_tran { get; set; }
        public int id_asset { get; set; }
        public int id_tran_status { get; set; }
        public Nullable<int> old_dept_id { get; set; }
        public Nullable<int> new_dept_id { get; set; }
        public Nullable<int> old_user_id { get; set; }
        public Nullable<int> new_user_id { get; set; }
        public string tran_type { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_approve> ext26_assetcontrol_approve { get; set; }
        public virtual ext26_assetcontrol_asset ext26_assetcontrol_asset { get; set; }
        public virtual ext26_assetcontrol_tran_status ext26_assetcontrol_tran_status { get; set; }
        public virtual ext26_assetcontrol_department ext26_assetcontrol_department { get; set; }
        public virtual ext26_assetcontrol_user ext26_assetcontrol_user { get; set; }
        public virtual ext26_assetcontrol_department ext26_assetcontrol_department1 { get; set; }
        public virtual ext26_assetcontrol_user ext26_assetcontrol_user1 { get; set; }
    }
}
