//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_hardware()
        {
            this.ext26_assetcontrol_hardware_log = new HashSet<ext26_assetcontrol_hardware_log>();
            this.ext26_assetcontrol_hardware_borrow = new HashSet<ext26_assetcontrol_hardware_borrow>();
            this.ext26_assetcontrol_hardware_borrow_log = new HashSet<ext26_assetcontrol_hardware_borrow_log>();
        }
    
        public int id_hardware { get; set; }
        public int id_type_hardware { get; set; }
        public string detail_hardware { get; set; }
        public int total_qty { get; set; }
        public int public_total_qty { get; set; }
        public bool public_all { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_log> ext26_assetcontrol_hardware_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow> ext26_assetcontrol_hardware_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow_log> ext26_assetcontrol_hardware_borrow_log { get; set; }
        public virtual ext26_assetcontrol_hardware_type ext26_assetcontrol_hardware_type { get; set; }
    }
}
