//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_asset_owner
    {
        public int id_owner { get; set; }
        public int id_asset { get; set; }
        public int id_user { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual ext26_assetcontrol_asset ext26_assetcontrol_asset { get; set; }
        public virtual ext26_assetcontrol_user ext26_assetcontrol_user { get; set; }
    }
}
