//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_borrow_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_borrow_status()
        {
            this.ext26_assetcontrol_asset_borrow = new HashSet<ext26_assetcontrol_asset_borrow>();
            this.ext26_assetcontrol_asset_borrow_log = new HashSet<ext26_assetcontrol_asset_borrow_log>();
            this.ext26_assetcontrol_hardware_borrow = new HashSet<ext26_assetcontrol_hardware_borrow>();
            this.ext26_assetcontrol_hardware_borrow_log = new HashSet<ext26_assetcontrol_hardware_borrow_log>();
        }
    
        public int id_status { get; set; }
        public string status_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow> ext26_assetcontrol_asset_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow_log> ext26_assetcontrol_asset_borrow_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow> ext26_assetcontrol_hardware_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow_log> ext26_assetcontrol_hardware_borrow_log { get; set; }
    }
}
