//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EXT26_ASSETCONTROLEntities : DbContext
    {
        public EXT26_ASSETCONTROLEntities()
            : base("name=EXT26_ASSETCONTROLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ext26_assetcontrol_approve> ext26_assetcontrol_approve { get; set; }
        public virtual DbSet<ext26_assetcontrol_approve_log> ext26_assetcontrol_approve_log { get; set; }
        public virtual DbSet<ext26_assetcontrol_approve_status> ext26_assetcontrol_approve_status { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset> ext26_assetcontrol_asset { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset_borrow> ext26_assetcontrol_asset_borrow { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset_borrow_log> ext26_assetcontrol_asset_borrow_log { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset_image> ext26_assetcontrol_asset_image { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset_log> ext26_assetcontrol_asset_log { get; set; }
        public virtual DbSet<ext26_assetcontrol_asset_owner> ext26_assetcontrol_asset_owner { get; set; }
        public virtual DbSet<ext26_assetcontrol_borrow_status> ext26_assetcontrol_borrow_status { get; set; }
        public virtual DbSet<ext26_assetcontrol_computer_spec> ext26_assetcontrol_computer_spec { get; set; }
        public virtual DbSet<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran { get; set; }
        public virtual DbSet<ext26_assetcontrol_department> ext26_assetcontrol_department { get; set; }
        public virtual DbSet<ext26_assetcontrol_hardware> ext26_assetcontrol_hardware { get; set; }
        public virtual DbSet<ext26_assetcontrol_hardware_borrow> ext26_assetcontrol_hardware_borrow { get; set; }
        public virtual DbSet<ext26_assetcontrol_hardware_borrow_log> ext26_assetcontrol_hardware_borrow_log { get; set; }
        public virtual DbSet<ext26_assetcontrol_hardware_log> ext26_assetcontrol_hardware_log { get; set; }
        public virtual DbSet<ext26_assetcontrol_hardware_type> ext26_assetcontrol_hardware_type { get; set; }
        public virtual DbSet<ext26_assetcontrol_role> ext26_assetcontrol_role { get; set; }
        public virtual DbSet<ext26_assetcontrol_software> ext26_assetcontrol_software { get; set; }
        public virtual DbSet<ext26_assetcontrol_status> ext26_assetcontrol_status { get; set; }
        public virtual DbSet<ext26_assetcontrol_tran_status> ext26_assetcontrol_tran_status { get; set; }
        public virtual DbSet<ext26_assetcontrol_type_computer> ext26_assetcontrol_type_computer { get; set; }
        public virtual DbSet<ext26_assetcontrol_user> ext26_assetcontrol_user { get; set; }
    }
}
