//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_asset_image
    {
        public int id_image { get; set; }
        public int id_asset { get; set; }
        public string image_name { get; set; }
        public string image_path { get; set; }
        public string image_type { get; set; }
    
        public virtual ext26_assetcontrol_asset ext26_assetcontrol_asset { get; set; }
    }
}
