//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_computer_spec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_computer_spec()
        {
            this.ext26_assetcontrol_asset = new HashSet<ext26_assetcontrol_asset>();
            this.ext26_assetcontrol_asset_log = new HashSet<ext26_assetcontrol_asset_log>();
        }
    
        public int id_com_spec { get; set; }
        public int id_type_com { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string cpu { get; set; }
        public string gpu { get; set; }
        public string memory { get; set; }
        public string disk_size { get; set; }
        public string os { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset> ext26_assetcontrol_asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_log> ext26_assetcontrol_asset_log { get; set; }
        public virtual ext26_assetcontrol_type_computer ext26_assetcontrol_type_computer { get; set; }
    }
}
