//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_hardware_borrow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_hardware_borrow()
        {
            this.ext26_assetcontrol_hardware_borrow_log = new HashSet<ext26_assetcontrol_hardware_borrow_log>();
        }
    
        public int id_borrow { get; set; }
        public int id_hardware { get; set; }
        public int id_user { get; set; }
        public int borrow_qty { get; set; }
        public System.DateTime borrow_date { get; set; }
        public System.DateTime due_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public int borrow_status { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        public virtual ext26_assetcontrol_borrow_status ext26_assetcontrol_borrow_status { get; set; }
        public virtual ext26_assetcontrol_hardware ext26_assetcontrol_hardware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow_log> ext26_assetcontrol_hardware_borrow_log { get; set; }
        public virtual ext26_assetcontrol_user ext26_assetcontrol_user { get; set; }
    }
}
