//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_approve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_approve()
        {
            this.ext26_assetcontrol_approve_log = new HashSet<ext26_assetcontrol_approve_log>();
        }
    
        public int id_approve { get; set; }
        public string emp_id { get; set; }
        public int id_computer_tran { get; set; }
        public int approve_ind { get; set; }
        public int approve_status { get; set; }
        public string remark { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        public virtual ext26_assetcontrol_approve_status ext26_assetcontrol_approve_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_approve_log> ext26_assetcontrol_approve_log { get; set; }
        public virtual ext26_assetcontrol_computer_tran ext26_assetcontrol_computer_tran { get; set; }
    }
}
