//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_department()
        {
            this.ext26_assetcontrol_computer_tran = new HashSet<ext26_assetcontrol_computer_tran>();
            this.ext26_assetcontrol_computer_tran1 = new HashSet<ext26_assetcontrol_computer_tran>();
        }
    
        public int id_dept { get; set; }
        public string code_dept { get; set; }
        public string dept_name { get; set; }
        public string factory { get; set; }
        public System.DateTime create_date { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran1 { get; set; }
    }
}
