//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_asset()
        {
            this.ext26_assetcontrol_asset_borrow = new HashSet<ext26_assetcontrol_asset_borrow>();
            this.ext26_assetcontrol_asset_borrow_log = new HashSet<ext26_assetcontrol_asset_borrow_log>();
            this.ext26_assetcontrol_asset_owner = new HashSet<ext26_assetcontrol_asset_owner>();
            this.ext26_assetcontrol_computer_tran = new HashSet<ext26_assetcontrol_computer_tran>();
            this.ext26_assetcontrol_asset_image = new HashSet<ext26_assetcontrol_asset_image>();
        }
    
        public int id_asset { get; set; }
        public string asset_number { get; set; }
        public string serial_number { get; set; }
        public int id_com_spec { get; set; }
        public int id_status { get; set; }
        public string dept { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow> ext26_assetcontrol_asset_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow_log> ext26_assetcontrol_asset_borrow_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_owner> ext26_assetcontrol_asset_owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_image> ext26_assetcontrol_asset_image { get; set; }
        public virtual ext26_assetcontrol_computer_spec ext26_assetcontrol_computer_spec { get; set; }
        public virtual ext26_assetcontrol_status ext26_assetcontrol_status { get; set; }
    }
}
