//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_type_computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_type_computer()
        {
            this.ext26_assetcontrol_computer_spec = new HashSet<ext26_assetcontrol_computer_spec>();
        }
    
        public int id_type_com { get; set; }
        public string type_computer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_spec> ext26_assetcontrol_computer_spec { get; set; }
    }
}
