//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetControl.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext26_assetcontrol_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ext26_assetcontrol_user()
        {
            this.ext26_assetcontrol_asset_borrow = new HashSet<ext26_assetcontrol_asset_borrow>();
            this.ext26_assetcontrol_asset_borrow_log = new HashSet<ext26_assetcontrol_asset_borrow_log>();
            this.ext26_assetcontrol_asset_owner = new HashSet<ext26_assetcontrol_asset_owner>();
            this.ext26_assetcontrol_computer_tran = new HashSet<ext26_assetcontrol_computer_tran>();
            this.ext26_assetcontrol_computer_tran1 = new HashSet<ext26_assetcontrol_computer_tran>();
            this.ext26_assetcontrol_hardware_borrow = new HashSet<ext26_assetcontrol_hardware_borrow>();
            this.ext26_assetcontrol_hardware_borrow_log = new HashSet<ext26_assetcontrol_hardware_borrow_log>();
        }
    
        public int id_user { get; set; }
        public string id_emp { get; set; }
        public string username { get; set; }
        public string user_password { get; set; }
        public string remark { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string cancel_by { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow> ext26_assetcontrol_asset_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_borrow_log> ext26_assetcontrol_asset_borrow_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_asset_owner> ext26_assetcontrol_asset_owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_computer_tran> ext26_assetcontrol_computer_tran1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow> ext26_assetcontrol_hardware_borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ext26_assetcontrol_hardware_borrow_log> ext26_assetcontrol_hardware_borrow_log { get; set; }
    }
}
